# Generated by Django 4.1.7 on 2023-04-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0005_rename_text_interpretation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='interpretations',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Interpretation',
        ),
    ]
